const routes = {
    home: '/',
    myAccount: '/student/my-account',
    myCourse: '/student/my-course',
    mySubmission: '/student/my-submission',
    changePassword: '/student/change-password',
    testPractice: '/student/test-practice',
    course: '/course',
    study: '/study',
    lesson: '/lesson',
    quizze: '/lesson/quizze',
    quizzeView: '/quizze/view',
    entryTest: '/entry-test',
    listeningPractice: '/test-practice/listening-practice',
    readingPractice: '/test-practice/reading-practice',
    speakingPractice: '/test-practice/speaking-practice',
    writingPractice: '/test-practice/writing-practice',
    ranking: '/ranking',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    blog: '/blog',
    news: '/news',
    aboutUs: '/about-us',
    privacyPolicy: '/privacy-policy',
    termAndCondition: '/term-and-condition',
    paymentPolicy: '/payment-policy',
    paymentStatus: '/payment/result',
}

export { routes }
